Software/autenticacao/urls.py
from django.urls import path
from . import views
from .views import UserRegisterWizard
from .forms import EmailForm, PasswordForm, NameForm

app_name = 'autenticacao'

urlpatterns = [
    path('', views.login, name='login'),
    path("cadastro/", UserRegisterWizard.as_view([EmailForm, PasswordForm, NameForm]), name="cadastro"),
    path('logout/', views.logout_view, name='logout'),
    path('tornar-autonomo/', views.solicitar_autonomo, name='solicitar_autonomo'),
]

Software/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('sobre/', views.sobre, name='sobre'),
    path('homeUser/', views.homeUser, name='homeUser'),
]

Software/projetoHelp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.http import HttpResponse

def my_view(request):
    return HttpResponse('Hello World!')

urlpatterns = [
    path('', include('home.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('hello/', my_view),
    path('admin/', admin.site.urls),
    path('sistema/', include('sistema.urls')),
]

Software/sistema/urls.py
from django.urls import path
from . import views

app_name = 'sistema'

urlpatterns = [
    path('home/', views.home_user, name='homeUser'),
    path('solicitar/', views.solicitar_servico, name='solicitar_servico'),
    path('atualizar/<int:servico_id>/', views.atualizar_servico, name='atualizar_servico'),
    path('deletar/<int:servico_id>/', views.deletar_servico, name='deletar_servico'),
    path('ver-proposta/<int:servico_id>/', views.ver_proposta, name='ver_proposta'),
    path('home-autonomo/', views.home_autonomo, name='home_autonomo'),
    path('solicitacoes-gerais/', views.solicitacoes_gerais, name='solicitacoes_gerais'),
    path('enviar-proposta/<int:servico_id>/', views.enviar_proposta, name='enviar_proposta'),
    path('recusar-oportunidade/<int:servico_id>/', views.recusar_oportunidade, name='recusar_oportunidade'),
]

Software/autenticacao/models.py
from django.db import models
from django.contrib.auth.models import User

class Perfil(models.Model):
    TIPO_USUARIO_CHOICES = [
        ('comum', 'Usuário Comum'),
        ('autonomo', 'Autônomo'),
    ]

    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    tipo_usuario = models.CharField(
        max_length=20,
        choices=TIPO_USUARIO_CHOICES,
        default='comum'
    )

    def __str__(self):
        return f"{self.usuario.username} ({self.get_tipo_usuario_display()})"

Software/autenticacao/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class EmailForm(forms.Form):
    email = forms.EmailField(label="E-mail")

class PasswordForm(forms.Form):
    password1 = forms.CharField(label="Senha", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirme a senha", widget=forms.PasswordInput)

class NameForm(forms.Form):
    first_name = forms.CharField(label="Nome")
    last_name = forms.CharField(label="Sobrenome")


# Formulário de Login que vamos adicionar
class LoginForm(forms.Form):
    username = forms.CharField(
        label='E-mail',
        widget=forms.TextInput()
    )
    password = forms.CharField(
        label='Senha',
        widget=forms.PasswordInput()
    )

class SolicitarAutonomoForm(forms.Form):
    mensagem = forms.CharField(
        label="Por que você quer se tornar autônomo?",
        widget=forms.Textarea(attrs={"rows": 4, "placeholder": "Descreva aqui..."})
    )

Software/autenticacao/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login, authenticate
from django.contrib import messages
from .forms import LoginForm, EmailForm, PasswordForm, NameForm
from django.contrib.auth import logout
from formtools.wizard.views import SessionWizardView
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from .forms import SolicitarAutonomoForm

class UserRegisterWizard(SessionWizardView):
    form_list = [EmailForm, PasswordForm, NameForm]
    template_name = "autenticacao/cadastro.html"

    def done(self, form_list, **kwargs):
        form_data = self.get_all_cleaned_data()
        user = User.objects.create_user(
            username=form_data["email"],
            email=form_data["email"],
            password=form_data["password1"],
            first_name=form_data["first_name"],
            last_name=form_data["last_name"],
        )
        return render(self.request, 'autenticacao/login.html', {"user": user})


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)

            if user is not None:
                auth_login(request, user)
                messages.success(request, 'Login realizado com sucesso!')
                return redirect('sistema:homeUser')
            else:
                messages.error(request, 'Usuário ou senha inválidos.')
    else:
        form = LoginForm()

    return render(request, 'autenticacao/login.html', {'form': form})


def logout_view(request):
    logout(request)
    messages.info(request, 'Você saiu do sistema.')
    return redirect('home:home')

@login_required
def solicitar_autonomo(request):
    if request.method == 'POST':
        form = SolicitarAutonomoForm(request.POST)
        if form.is_valid():
            mensagem = form.cleaned_data['mensagem']
            send_mail(
                subject='Solicitação de conta Autônomo',
                message=f"O usuário {request.user.username} ({request.user.email}) solicitou se tornar autônomo.\n\nMensagem:\n{mensagem}",
                from_email='seuemail@gmail.com',
                recipient_list=['jonatascontateste01@gmail.com'],
            )
            messages.success(request, 'Sua solicitação foi enviada com sucesso!')
            return redirect('sistema:homeUser')
    else:
        form = SolicitarAutonomoForm()
    return render(request, 'autenticacao/solicitar_autonomo.html', {'form': form})

Software/autenticacao/templates/autenticacao/cadastro.html
{% extends 'global/partials/base.html' %}

{% block nav %}
    {% include 'global/partials/nav.html' %}
{% endblock nav %}

{% block title %}Cadastro | {% endblock title %}

{% block content %}
<div class="form-wrapper">
    <h2>Crie sua conta</h2>
    <p>Preencha os campos abaixo para se cadastrar no sistema.</p><br>

    <form method="post">
        <div class="form-group">
            {% csrf_token %}
            {{ wizard.management_form }}
            {{ wizard.form.as_p }}
            <br>
            <button type="submit" class="btn btn-primary">Próximo</button>
        </div>
    </form>

    
    <p class="center">Já tem uma conta? <a href="{% url 'autenticacao:login' %}">Faça seu login.</a></p>
</div>
{% endblock content %}

Software/autenticacao/templates/autenticacao/login.html
{% extends 'global/partials/base.html' %}

{% block nav %}
    {% include 'global/partials/nav.html' %}
{% endblock nav %}

{% block title %}Login | {% endblock title %}

{% block content %}
<div class="main-content container">
    {% if messages %}
        <ul class="messages-container">
            {% for message in messages %}
                <li class="message {{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</div>

<div class="form-wrapper">
    <h2>Acesse sua conta</h2>
    <p>Digite seu E-mail e Senha para entrar.</p><br>

    <form method="POST" action="{% url 'autenticacao:login' %}">
        {% csrf_token %}
        
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {{ field.errors }}
            </div>
        {% endfor %}
        
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Entrar</button>
        </div>
    </form>
</div>
{% endblock content %}

Software/autenticacao/templates/autenticacao/solicitar_autonomo.html
{% extends 'global/partials/base.html' %}

{% block nav %}
    {% include 'global/partials/navUser.html' %}
{% endblock nav %}

{% block title %}Tornar Autônomo | {% endblock title %}

{% block content %}
<div class="form-wrapper">
    <h2>Solicitar acesso como Autônomo</h2>
    <p>Preencha o campo abaixo para enviar sua solicitação.</p><br>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Enviar solicitação</button>
    </form>

    <p class="center"><a href="{% url 'sistema:homeUser' %}">Voltar</a></p>
</div>
{% endblock content %}